name: N1 OpenWrt CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  FILES_PATH: files
  TZ: Asia/Shanghai
  CCACHE_DIR: /tmp/ccache
  CCACHE_MAXSIZE: 2G

jobs:
  build:
    name: Build OpenWrt
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: openwrt
        submodules: recursive

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v2
      with:
        swap-storage: false  # 避免影响编译稳定性

    - name: Setup environment
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo apt-get -qq update
        sudo apt-get -qq install \
          build-essential clang flex bison g++ gawk gcc-multilib gettext \
          git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip \
          zlib1g-dev file wget qemu-utils upx-ucl libelf-dev openjdk-17-jdk \
          ccache cmake curl libxml2-utils lzma python3.9-venv

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-ccache-openwrt

    - name: Clone OpenWrt
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply config
      run: |
        cp ${{ github.workspace }}/openwrt/$CONFIG_FILE lede/.config
        cp -rf ${{ github.workspace }}/openwrt/$FILES_PATH lede/package/

    - name: Update kernel config
      run: |
        cd lede
        sed -i "s/CONFIG_KERNEL_BUILD_USER=.*/CONFIG_KERNEL_BUILD_USER=\"GitHub Actions\"/" .config
        sed -i "s/CONFIG_KERNEL_BUILD_DOMAIN=.*/CONFIG_KERNEL_BUILD_DOMAIN=\"CI\"/" .config
        make defconfig

    - name: Download dependencies
      run: |
        cd lede
        make -j$(nproc) download

    - name: Build firmware
      run: |
        cd lede
        echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV
        ccache -s
        make -j$(($(nproc) + 1)) V=s \
          CONFIG_SIGNED_PACKAGES= \
          CONFIG_SIGNATURE_CHECK=

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: openwrt_bin
        path: |
          lede/bin/targets/**/*
          !lede/bin/targets/**/*.manifest
          !lede/bin/targets/**/*.buildinfo
        retention-days: 7

    - name: Upload ccache
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: ccache
        path: /tmp/ccache
        retention-days: 1
